language: r
r: devel
sudo: FALSE
cache: packages

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_github_packages:
  - hadley/devtools@efa894ffa
