language: 
  - R

cache: 
  - packages
  
sudo:
  - required

warnings_are_errors: 
  - true

script:
  - ./travis-tool/travis_timeout.sh travis_wait

## Use patched devtools
r_github_packages:
  - hadley/devtools@efa894ffa
